# Generated by Django 5.2.5 on 2025-08-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='external_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
