# Generated by Django 5.2.5 on 2025-08-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='external_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('subject', 'external_id'), name='uq_subject_external_id'),
        ),
    ]
